### ISSUE TITLE
Change repo/project name

### ISSUE THREAD

**Issue by illepic** [phase2/pattern-lab-starter#119]
This is a Drupal theme. It is mostly about static asset generation, with a pattern lab integration as a development helper tool. "Pattern Lab" in the project name seems to cause some folks confusion. Whereas, "small twig files in a folder" is less offensive for some reason.

Name change ideas in the comments below ⬇️ . One suggestion per comment, vote with thumbs up/down emoji.

**Comment by illepic** [comment]
Atomic

**Comment by illepic** [comment]
Just-A-Buncha-Twig-Files

**Comment by illepic** [comment]
Design System First

**Comment by anniegreens** [comment]
Matryoshka (aka Russian nesting doll)

**Comment by anniegreens** [comment]
Naming Things is Hard

**Comment by anniegreens** [comment]
Schema (In psychology and cognitive science, a schema (plural schemata or schemas) describes a pattern of thought or behavior that organizes categories of information and the relationships among them.)

**Comment by jryanconklin** [comment]
Motif

**Comment by jryanconklin** [comment]
Swatch

**Comment by anniegreens** [comment]
Stitch

**Comment by grayside** [comment]
Per a discussion just now, find and replace of the name may be important.

Visualize, Cue, Papyrus, [Lascaux](https://en.wikipedia.org/wiki/Lascaux), [Dwiggins](https://en.wikipedia.org/wiki/William_Addison_Dwiggins), Beholder, Planner, Scapegoat, Stunning, Aspire

**Comment by grayside** [comment]
Visualize

**Comment by grayside** [comment]
Papyrus

**Comment by grayside** [comment]
Beholder

**Comment by grayside** [comment]
Planner

**Comment by grayside** [comment]
Scapegoat

**Comment by grayside** [comment]
Stunning

**Comment by grayside** [comment]
Aspire

**Comment by geoff-winner** [comment]
I like something water related, being as it's a Drupal theme..

Thermocline?

**Comment by tjheffner** [comment]
breadbox

**Comment by jryanconklin** [comment]
Impact

**Comment by anniegreens** [comment]
Paddle

**Comment by illepic** [comment]
Myriad

**Comment by jryanconklin** [comment]
Foundry (From Octane Naming Discussion)

**Comment by amitchell-p2** [comment]
Embark

**Comment by amitchell-p2** [comment]
Sprig

**Comment by amitchell-p2** [comment]
Fount

**Comment by anniegreens** [comment]
Particle

**Comment by anniegreens** [comment]
Variance

**Comment by tjheffner** [comment]
jib 

SAILING
1. a triangular staysail set forward of the forwardmost mast.
2. the projecting arm of a crane.

**Comment by jdcrisamore** [comment]
'Matrix'
Definition: something that constitutes the place or point from which something else originates, takes form, or develops.

'Forge'
Definition: to form or make, especially by concentrated effort.

**Comment by jdcrisamore** [comment]
'Forge'
Definition: to form or make, especially by concentrated effort.

**Comment by hey-ape** [comment]
Elemental or Elemental Design

**Comment by scottalan** [comment]
Fire Starter

**Comment by bkildow** [comment]
Hydrocarbon

**Comment by mikecrittenden** [comment]
Auger - a wood ("twig") boring device or bit.

**Comment by scottalan** [comment]
paragon

> a model or pattern of excellence or of a particular excellence

**Comment by scottalan** [comment]
cynosure

http://www.dictionary.com/browse/cynosure

**Comment by grayside** [comment]
If you thought Scapegoat was good, try **apocryphal**

**Comment by grayside** [comment]
particulate

**Comment by grayside** [comment]
particle

**Comment by aimenkhakwani** [comment]
Ripple

**Comment by tjheffner** [comment]
hatch

**Comment by illepic** [comment]
Inspired by the [conference held **just** for design systems](https://www.clarityconf.com/):

>CLARITY

**Comment by jryanconklin** [comment]
Thundersnow (Because codenames become real names too)

**Comment by srjosh** [comment]
Biosphere (One step up from @organism)

**Comment by tjheffner** [comment]
https://www.surveymonkey.com/r/799BBRN i started an anonymous randomized survey that has all options receiving at least 1 vote to this point. please vote here also, multiple selections just fine.

**Comment by anniegreens** [comment]
Closing issue. Please vote at survey monkey link.
