### ISSUE TITLE
Look into incorporating Autoprefixer into workflow

### ISSUE THREAD

**Issue by fillerwriter** [phase2/pattern-lab-starter#12]
https://github.com/postcss/autoprefixer

It gets us a more automatic way of adding browser-specific prefixes for various CSS experimental features, which should help with overall code quality. Also, [Bourbon is apparently going to phase out their prefix support in 5.0](https://github.com/thoughtbot/bourbon/issues/702), and we should start thinking about how we want to handle that.

**Comment by EvanLovely** [comment]
It's in!
