### ISSUE TITLE
Use webpack "resolve" to shorten js paths

### ISSUE THREAD

**Issue by rloos289** [phase2/pattern-lab-starter#139]
At the moment we import JS components through statements like `import card from './_patterns/02-molecules/card/card';`, we'd prefer to use webpback's resolve plugin to instead use something linke `import card from '@molecules/card'`. Unfortunately this runs into issues with our linter (see [this link](https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-284216693) for discussion). The issue is that our webpack config is written in ES6 and the linter can only understand if its in ES5 (see [here](https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-284216693)). So far, possible solutions seem to be either to re-write the webpack config, or to use babel to translate the ES6 into ES5.

**Comment by illepic** [comment]
This is now solved on this commit: https://github.com/phase2/pattern-lab-starter/pull/140/commits/7b52f5a9da347dcf805cf8f043fb80c1c82f7227
