### ISSUE TITLE
Elevator pitch me, bro! (aka, documentation)

### ISSUE THREAD

**Issue by fillerwriter** [phase2/pattern-lab-starter#14]
As I'm looking at the various pieces of functionality in the Gruntfile (and subfiles), the various packages that we download via npm and bower, and the many, many lines of code that are available inside the incorporated PatternLab folder, it occurs to me that the only thing I really know about the actual functionality of this project is the presentation that @EvanLovely and @illepic gave at P2Con.

In the README, I think we should add a section near the top of the page that explains exactly all the things that you get for for free in addition to the usual PatternLab stuff. From what I remember and have sussed out, we should mention...

- Bourbon!
- Autoprefixer! (thanks #12)
- SCSS/JS linting!
- SVG to font icons!
- Extendable Grunt tasks!
- The undying love of the P2 Design Implementation concentration group for being beta testers!

**Comment by EvanLovely** [comment]
Love it! I'm definitely on board for getting docs up and going. I also want to get a roadmap rolling. There are docs in the images atom page in PL for how to use icon system, we should get the overview into the readme. Probably need to make a section for "features".  

Here's some of the main features:

* Grunt setup to compile PL & Scss with options to use the faster libsass or Ruby & Compass
* Error linting of last file saved for js, scss, and json
* Icon system - Just drop a SVG into a folder for this:
	* SVGs converted to Font Icons
	* Creates Scss Mixin and Class based on filename
	* Adds demo icon to Pattern Lab “icons” page
* Automatic updates of Pattern Lab’s style guide based on Scss
	* Colors
	* Font Families & Typography Sizes
	* Breakpoints
	* Easy to add more
* Bower Component’s HTML tags auto-added to Pattern Lab

**Comment by nielsonm** [comment]
PR #26 Submitted.
