### ISSUE TITLE
Concurrent linting

### ISSUE THREAD

**Issue by grayside** [phase2/pattern-lab-starter#143]
In #132 the goal was to make sure all the things are lined at once. While linting output should be sequential for readability, might there be a way to run these concurrently?

If not across lining tools, then consider this also an issue in making sure the individual processes parallelize on the file level. For example, the parallel-lint project for PHP code.

**Comment by illepic** [comment]
Solving this for now via `&` instead of `&&` at the npm script level via this commit in the bootstrap work: https://github.com/phase2/pattern-lab-starter/pull/140/commits/f83b9ff187c1a0b6caf5236a6aade6507ee5e1fd

```json
"lint": "npm run lint:js & npm run lint:scss",
```
