### ISSUE TITLE
Auto-detect Drupal 7 or 8

### ISSUE THREAD

**Issue by EvanLovely** [phase2/pattern-lab-starter#3]
Currently the name of the Drupal 7 `.info` file is hard coded. I'd like to trigger Drupal 7 or Drupal 8 "mode" based on the presence, or lack of, that file (or its Drupal 8 equivalent). The name should be auto-detected as well.

**Comment by grayside** [comment]
Maybe https://github.com/phase2/grunt-drupal-tasks/blob/master/lib/drupal.js could provide a trick? Or even more thoroughly, we could extract that as a node library for node-based Drupal utilities.

**Comment by EvanLovely** [comment]
Thanks! I like the idea of a stand alone utility to detect Drupal versions. I bet @jhedstrom would be really interested in this as well.

**Comment by EvanLovely** [comment]
This'll get handled by the yeoman generator: https://github.com/phase2/generator-pattern-lab-starter/
