### ISSUE TITLE
Searching for the big picture

### ISSUE THREAD

**Issue by wearymadness** [phase2/pattern-lab-starter#36]
I'm really keen to understand what this does, but the docs don't make it immediately clear. 

What is the relation of this starter to the Drupal install (if any)? Do I create a theme and unpack and run the npm/bower commands there?

I may be well of the mark as to what this software does, if so, I apologies.

TANX
weary

**Comment by EvanLovely** [comment]
Hi! This repos get cloned and setup by our Yeoman generator and the readme you see at the root of this repo is for others using what is already set up. Head here and follow the instructions: https://github.com/phase2/generator-pattern-lab-starter
