### ISSUE TITLE
Question about templates

### ISSUE THREAD

**Issue by alioso** [phase2/pattern-lab-starter#39]
Hey Evan, great work here! Been experimenting with similar ways of pairing Pattern Lab w/ Drupal and I am still very much wondering what the best way to do it is so it actually makes sense in how we manipulate data. Was at DrupalCon and obviously lots of talks about it, sessions and ideas being exchanged. 

I like the idea about not duplicating templates (which in my opinion should be avoided for sure), but isn't including a twig file in an empty .html.twig essentially duplicating it? Sure, you can add certain attributes, but nothing that couldn't be done if all code lived in one and only .html.twig, right? Unless I am missing something, why not having pattern-lab ready our html.twig templates and rendering that and using json files to populate static content (or the Data Transform Plugin). We can then get rid of the component module, Drupal will actually read the templates located within the /pattern-lab/source/_patterns/ or anywhere else for that matter and Pattern Lab will be just fine with using html.twig files. 

I have the feeling that perhaps we want to actually use .twig files to actually write vanilla twig and include that in our .html.twig? If so, what are the advantages of using native twig files exactly? What else am I missing here?

All burning questions that do not criticize your method at all! Just trying to find a workflow I can work towards sustainably and can expect to not remodel too often. So much of this is in its infancy. 

Thanks!

**Comment by EvanLovely** [comment]
Thanks!! The reasoning is that you can include your components in multiple other templates (we want *reusable* components, right? not just nested includes). The Pattern Lab twig files are pure, clean component templates and the Drupal templates are the Presenter layer in the [Model View Presenter](https://en.wikipedia.org/wiki/Model–view–presenter) pattern. Those Drupal template files could potentially get different data models tossed at them and still include the same components (so you could include a Card component from Pattern Lab in a Panels template and a View template and translate the data needed for the Card template in each).

So I won't be able to respond again for the next 3 weeks as I'm just starting my Paternity Leave (first kid!!), however @illepic can answer some more questions related to this. Thanks for the interest!! :beers:

**Comment by alioso** [comment]
This makes perfect sense. Thanks again!

**Comment by alioso** [comment]
And congrats!!!

**Comment by EvanLovely** [comment]
Great!! Thanks!
