### ISSUE TITLE
Error on windows using cmder , No such file or directory

### ISSUE THREAD

**Issue by drupalshift** [phase2/pattern-lab-starter#41]
Hi there , i get this warning whenever changing a file 

`Warning: rmdir(E:/pground/phase2/pattern-lab\public/patterns\02-molecules-caption-block-caption-block): No such file or directory in E:\pground\phase2\pattern-lab\vendor\pattern-lab\core\src\PatternLab\FileUtil.php on line 200`

How can i fix this !? something is wrong with those trailing slashes i think ( `phase2/pattern-lab\public/` )

**Comment by dmolsen** [comment]
This may or may not work but it looks like `composer.lock` is set for `v2.2.1` of Pattern Lab. `v2.3.0` fixed a lot of those slash issues. You might be able to go into `./pattern-lab` and run `composer update pattern-lab/core` to upgrade.

**Comment by drupalshift** [comment]
@dmolsen Updating pattern-lab core solved my problem , Thanks <3
