### ISSUE TITLE
Templates not defined 

### ISSUE THREAD

**Issue by pauwlsky** [phase2/pattern-lab-starter#42]
Hello,
Thanks for going to all the work to put this together, really is an awesome templating tool. 
I have been using PL 1.0 with mustache and recently made the conversion to learning twig and working with PL 2.0. I cloned this theme into an existing project and have installed it, I'm running into this error from the landing page when logged into my admin account: 

`Template "@molecules/branding/branding.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@molecules/branding/branding.twig" in the Drupal theme registry.) in "themes/contrib/pattern-lab-starter/templates/block--system-branding-block.html.twig" at line 18.`

Can you recommend a fix? Thanks again.

**Comment by dotmagic** [comment]
Sounds like you didn't enable the components module? Just follow the Readme.md
https://www.drupal.org/project/components

**Comment by EvanLovely** [comment]
@dotmagic is correct; let us know if you have any other problems @pauwlsky !

**Comment by pauwlsky** [comment]
Thanks for the replies you guys :) I got it up and running !

**Comment by origindesign** [comment]
@pauwlsky was the module not being enabled your issue in the end? I am facing the same error message, but I do have the components module enabled.
