### ISSUE TITLE
The npm dependencies for pattern-lab-starter create 135895 files

### ISSUE THREAD

**Issue by mathieuhelie** [phase2/pattern-lab-starter#43]
This is causing our development VMs and IDEs to spin crazily trying to index all those files.

As a base of comparison, Drupal 8 core has 12967 files and its vendor dir installs 12467 files, and it's starting to strain our tools.

As is this project is not useable for us, unfortunately.

**Comment by drupalshift** [comment]
You can exclude those folders from indexing for example in PhpStorm , right click > mark directory as > excluded , it stops indexing , if you need to develop for drupal ( modules and etc ) you don't need to open drupal as project you can create a drupal project in PhpStorm OR include drupal apis in your ide as reference ,  anyway currently im working on a drupal project ( organization portal ) which has over 200 designs and 38 custom modules up to now , my development machine has 4GB Ram and Core i5 CPU , it's more than enough for my situation , i'm sure you can tweak your workflow , if you explain your situation maybe i can help

**Comment by EvanLovely** [comment]
Yep, I totally agree with that solution: ignore the `node_modules` directory from your IDE. The main dependency installed is our [`p2-theme-core`](https://github.com/phase2/p2-theme-core) which in turn installs most of the Gulp dependencies needed for front end development: Sass, AutoPrefixer via PostCSS, SVG to Font Icon conversion, JS compilation via Babel, and BrowserSync style injection and live reload. I'd like to break that main dependency up so you could pick and choose which features you'd like and only install those dependencies. 

Additionally, you could remove the Gulp and npm dependencies and simply compile Pattern Lab with:

    php pattern-lab/core/console --generate

A watch can be fired off with:

    php pattern-lab/core/console --watch

And a server can be fired off with:

    php pattern-lab/core/console --server

After that, just set up your own Scss compiling and you should be good to remove all npm dependencies. There's a lot of fine detail figured out already though, so I'd suggest leaving it and simply ignoring the `node_modules` folder like suggested, but it's possible to roll your own toolset. Happy Pattern Labbing!
