### ISSUE TITLE
Is there a version of this that works on drupal 7?

### ISSUE THREAD

**Issue by thangarajj** [phase2/pattern-lab-starter#44]
If not maybe you can suggest any existing library to use pattern lab with drupal 7..?

Thank you!
Thangaraj

**Comment by drupalshift** [comment]
it's working with drupal 7

**Comment by EvanLovely** [comment]
Yep, this works with Drupal 7 as a theme starter using Pattern Lab that shares CSS between the two. However, to have unified Twig templates, that will require Drupal 8 as Drupal 7 does not use Twig templates. Happy Pattern Labbing!
