### ISSUE TITLE
Recommended Workflow for working with templates

### ISSUE THREAD

**Issue by webcultist** [phase2/pattern-lab-starter#51]
My current understanding of using the pattern lab patterns in the Drupal templates in pattern-lab-starter is the following: 
Create the component -> style it -> create the correct Drupal template file with the necessary name and extend the component. Is that correct? 

The guys from forum one described in their session at the DrupalCon that they copy every template file automatically into the template folder and just keep the names for the patterns like the Drupal templates (https://events.drupal.org/neworleans2016/sessions/big-easy-front-end-development-pattern-lab-and-twig). 
Do you guys use such a workflow or would it be a good extension? Is there maybe already such a workflow integrated and I just don't get it? ^^

Thanks in advance for the answer!

**Comment by illepic** [comment]
Hello @webcultist, take a look at our demo implementation repo here https://github.com/phase2/drupal-lab. You'll note that Drupal requires the Components module installed, but you'll be able to @include/@extend/@embed any Pattern Lab twig file and pass it data from Drupal.

Note the `@embed with` here: https://github.com/phase2/drupal-lab/blob/master/web/themes/dashing/templates/content/node--article--teaser.html.twig

**Comment by webcultist** [comment]
I close this now as it is clear.
