### ISSUE TITLE
how can ignore injected files?

### ISSUE THREAD

**Issue by ensk** [phase2/pattern-lab-starter#63]
the injectpl function adds all css and js files in dest folder..but how can ignore some files ?
what i try...in `gulpconfig.js` inside `patternlab` i added `ignorePath: ['../../dest/page.layout.simple-fluid.css']`, but didn't work, what is the correct way ? thanks for help

**Comment by jerseycheese** [comment]
@EvanLovely I'm also having this issue - any idea?

**Comment by EvanLovely** [comment]
Inside `gulpconfig.js` in the `patternLab.injectFiles` array, add a `!` before the path you want to exclude. Remember that paths are relative to `gulpfile.js`. So like this:

```js
patternLab: {
  injectFiles: [
    '!dest/page.layout.simple-fluid.css'
  ]
}
```
