### ISSUE TITLE
Normalize config

### ISSUE THREAD

**Issue by anniegreens** [phase2/pattern-lab-starter#67]
It appears new versions of Normalize provide configuration, so inclusion of the base `_normalize.scss` no longer compiles on its own.

We should investigate config options, if that is desired, or simply update the `@import` in `style.scss` to `@import "normalize-scss/sass/normalize/import-now";`. See the Normalize readme for further information under "Approach 2".

**Comment by illepic** [comment]
Going to drop this one since starting PL starter will have bootstrap 4 goodies, including [reboot.css](https://scotch.io/tutorials/a-look-at-bootstrap-4s-new-reset-rebootcss)
