### ISSUE TITLE
Allow external links in PL components to work

### ISSUE THREAD

**Issue by EvanLovely** [phase2/pattern-lab-starter#7]
How to reproduce:

1. Fire up the site with `grunt`
2. Place a link in any `.mustache` file
3. Click it and notice that it doesn't open

This has to do with the patterns existing in an `<iframe>`. Would prefer for it to open in a new tab.

It looks like this is an open issue with a posted solution on pattern-lab/patternlab-php#234

**Comment by nielsonm** [comment]
@EvanLovely Mind if I grab this?

**Comment by EvanLovely** [comment]
@nielsonm That would be awesome!
