### ISSUE TITLE
Things to look for on gulp upgrade

### ISSUE THREAD

**Issue by tekante** [phase2/pattern-lab-starter#77]
Our generator will insert a CHOKIDAR_USEPOLLING environmental variable into the build container yml file. This is because gulp uses CHOKIDAR under the covers for filesystem watches and inside our build container polling needs to be used because both filesystem events aren't supported on linux by this library and because code mounted over NFS doesn't trigger events anyway.

Gulp appears as though it's going to be moving to graze on the next version (see https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb docs about options being passed to graze) and when we update to using it we'll need to reassess our filesystem watch configuration.

**Comment by EvanLovely** [comment]
We're already using the next version, Gulp 4. The [docs for v4 are here](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md). We could simply use `process.env.CHOKIDAR_USEPOLLING` in the code for the watches, but that'd be on `p2-theme-core` repo.
