### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by EvanLovely** [phase2/pattern-lab-starter#8]
I'd like to get automatic syntax highlighting going using [Highlight.js](https://highlightjs.org) for code blocks in patterns.

**Comment by nielsonm** [comment]
@EvanLovely Mind if I grab this?

**Comment by EvanLovely** [comment]
@nielsonm This would also be very awesome! It'd be super helpful with lots of code samples and demos. 

Evan Lovely
Senior Front End Developer | Phase2
(t) @EvanLovely

@Phase2

DC | NYC | SF | PDX | EVERYWHERE
