### ISSUE TITLE
Routing back to home is broken on the guide pages

### ISSUE THREAD

**Issue by MaffooBristol** [phase2/pattern-lab-starter#86]
Not sure where to put this because the code seems to be dotted about, but I've noticed a bug where, if you are viewing the pattern guide itself at `http://localhost:3050/pattern-lab/public/` and you click onto a route, say `/pattern-lab/public/?p=base-colors`, then hit back, nothing happens. Is this a known fault?

Thanks
Matt

**Comment by illepic** [comment]
Just following up here that I cannot verify this bug. I can view colors, hit back, and see public again. I'll close this in a few weeks if no response. (Sorry for the delay here)

**Comment by MaffooBristol** [comment]
I'll see if I can do some further research into it and give you a recreatable case in the next week or so. If I forget then feel free to close!

**Comment by illepic** [comment]
Thanks @MaffooBristol !
