### ISSUE TITLE
Adding external Javascript 

### ISSUE THREAD

**Issue by origindesign** [phase2/pattern-lab-starter#90]
I have an external js file to handle font loading. On Drupal, it's added through my-theme.libraries.yml but it's obviously not recognized by pattern-lab. How do you add it to Pattern Lab so it can be included in the preview?

**Comment by geoff-winner** [comment]
Hey @origindesign ,

Where does this JS file live? If you look in `gulpconfig.js` in the root of the theme on line 47 you can see there are different configuration options for JS. You might make sure that the path to this JS file is included in your `src: []`.

**Comment by origindesign** [comment]
That's the thing. It's an external script, it lives on fonts.com CDN.
Is it recommended to download any CDN hosted js, locally?

**Comment by tjheffner** [comment]
That's one option to get files loaded in PL, but shouldn't be necessary here. You can load CDN hosted files inside PL through this file: https://github.com/phase2/pattern-lab-starter/blob/master/source/_meta/_00-head.twig

As long as you don't put the CDN link inside the  ```<!-- inject:css -->``` tags, it should work just fine.

**Comment by origindesign** [comment]
Perfect, this is exactly what I was looking for. Thanks.
